### ISSUE TITLE
Beware of libraries that assert on property access, augment chai with dirty-chai

### ISSUE THREAD

**Issue by AllenBW** [ManageIQ/manageiq-ui-service#1129] opened 2017-10-23 13:42 UTC
https://github.com/moll/js-must#asserting-on-property-access

https://www.npmjs.com/package/dirty-chai

https://github.com/standard/standard/issues/690#issuecomment-278533482

**Comment by chriskacerguis** [comment] 2017-11-16 15:43
Not 100% sure what the issue is here.  Going to close this, please open a BZ if needed.

**Closed by chriskacerguis** 2017-11-16 15:43 UTC
Labels: technical debt
